# Generated by Django 2.1 on 2019-01-21 17:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 17, 53, 34, 358048, tzinfo=utc), verbose_name='date published'),
        ),
    ]
