# Generated by Django 2.1 on 2019-01-22 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_tweet_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 22, 13, 50, 28, 301969, tzinfo=utc), verbose_name='date published'),
        ),
    ]
